FROM python:3.9-slim
WORKDIR /app

COPY proxy/requirements.txt .
RUN pip install -r requirements.txt

RUN mkdir -p /app/data && chmod 777 /app/data

COPY proxy/app.py .

COPY shared/ /app/shared/

CMD ["python", "app.py"]